version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/back-end"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "daily"
